### ISSUE TITLE
README.md is rendered incorrectly on pub.dev and in API docs

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/characters#83] opened 2023-05-21 03:13 UTC
`package:characters`'s `README.md` is rendered incorrectly on pub.dev:

https://pub.dev/packages/characters

which currently shows up as:

![image](https://github.com/dart-lang/pub-dev/assets/17391434/6436e79b-a097-4faa-8184-0e1725dbf85d)

[The API documentation](https://pub.dev/documentation/characters/latest/) is rendered a bit better but is still wrong:

![image](https://github.com/dart-lang/characters/assets/17391434/94fcc067-5d01-41fd-b6b3-7922b0fb886f)

That section is not intended to be visible; it's supposed to be a footnote section that provides only URLs for other links in the document.

The `README.md` appears fine on GitHub, however.

Maybe `package:markdown` is confused by the quoted strings in the footnote section?

(This probably is an issue with `package:markdown`, and maybe with pub.dev since it's rendering worse than dartdoc (maybe using a different version of `markdown`?), but I'm filing it here because it's probably easier and more practical to tweak the `README.md` file.)

**Comment by devoncarew** [comment] 2023-05-23 15:50
Thanks for the report! Closing as I think the issue is in package:markdown - https://github.com/dart-lang/markdown/issues/546.

**Comment by jamesderlin** [comment] 2023-05-23 16:43
Yes, I agree it's a problem in `package:markdown`, but as I mentioned, the `README.md` is pretty unreadable on pub.dev right now, so unless https://github.com/dart-lang/markdown/issues/546 is expected to be fixed soon (it's currently marked P3), it'd probably be faster to tweak the `README.md` file.

**Comment by erf** [comment] 2023-07-08 16:53
Documentation is not working now, i guess it's related to this issue.

E.g.:
https://pub.dev/documentation/characters/latest/characters/CharacterRange/replaceRange.html

Yields: "404 Not Found"

**Closed** 2024-01-29 20:23 UTC
