### ISSUE TITLE
Add and improve index based APIs

### ISSUE THREAD

**Issue by JulianBissekkou** [dart-lang/characters#15] opened 2020-01-07 07:11 UTC
The current `String` class provides many index-based APIs that are nice when manipulating strings, for example `substring`. We are using that in combination with regular expressions that help us determine where to split a string or where to replace specific content.

Example:
```dart
final nextUserNameLink = message.substring(currentIndex, match.start)
```
Solving this with the current character API is really tricky since you can not work with the index provided by `match`.

Maybe I am missing something, but it would be nice to have a save `substring` API for characters!

**Comment by lrhn** [comment] 2020-02-10 13:38
An index-based API is a deliberate non-goal for the `Characters` class. 
It's not impossible (the earlier versions of the API did use indexes), but it also means that using any index that is not on a grapheme cluster boundary has unexpected behavior. 

Since regular expressions are not grapheme cluster aware, using them become dangerous.

If you need to use `substring`, you can still do that on the *string*. So `Characters c = ...; c = c.string.substring(...).characters;` should work. You do not get any enforcement of working on grapheme clusters only, but that's always an issue with using indices.

**Comment by mit-mit** [comment] 2020-05-26 17:11
Closing as by-design

**Closed by mit-mit** 2020-05-26 17:11 UTC
